name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Install dependencies
      run: |
        npm ci
        npm install -g @nativescript/cli

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Decode Keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo "$KEYSTORE_BASE64" | base64 -d > android-keystore.jks

    - name: Build Android
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        ns build android --release \
          --key-store-path android-keystore.jks \
          --key-store-password "$KEYSTORE_PASSWORD" \
          --key-store-alias "$KEYSTORE_ALIAS" \
          --key-store-alias-password "$KEY_PASSWORD"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
        retention-days: 7